CoffeeShop/CoffeeShop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from NeoCoffee import views as neo_views
from django.views.generic import RedirectView
from Shopping import views as shp_views

urlpatterns = [
    path('', RedirectView.as_view(url='/categories/')),
    path('admin/', admin.site.urls),
    path('categories/', neo_views.show_categories, name='show_categories'),
    path('api/topcategories/', neo_views.top_categories, name='top_categories'),
    path('api/subcategories/<int:parent_id>/', neo_views.sub_categories, name='sub_categories'),
    path('Shopping/', include('Shopping.urls')),
    path('api/place_order/', shp_views.place_order, name='place_order'),
    path('orders/', shp_views.order_list, name='order_list'),
]

CoffeeShop/Shopping/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = 'Shopping'

urlpatterns = [
    path('', RedirectView.as_view(url='/Shopping/login'), name="index"),
    path('register', views.sign_up, name='Register'),
    path('login', views.sign_in, name='Login'),
    path('logout', views.log_out, name='Logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

CoffeeShop/Shopping/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Member(models.Model):
    member_name = models.CharField(max_length=200, help_text='Enter Member name')
    member_number = models.CharField(max_length=10, help_text='Enter phone number')
    member_address = models.CharField(max_length=200, help_text='Enter address')
    member_email = models.EmailField(max_length=200, help_text='Enter email')

    def __str__(self):
        return self.member_name

    class Meta:
        ordering = ['member_name']

    def get_absolute_url(self):
        return reverse("member_detail", args=[str(self.id)])

class Order(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    coffee_name = models.CharField(max_length=200, help_text='Enter coffee name')

    def __str__(self):
        return self.member.member_name
    
    permissions = [
            ("can_add_order", "Can add order"),
            # Other permissions...
        ]

CoffeeShop/Shopping/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):

    accountname = forms.CharField(
        label="姓名",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    username = forms.CharField(
        label="帳號",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    email = forms.EmailField(
        label="電子郵件",
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )

    address = forms.CharField(
        label="地址",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    number = forms.CharField(
        max_length=11,
        label = "電話",
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    password1 = forms.CharField(
        label="密碼",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    password2 = forms.CharField(
        label="密碼確認",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    class Meta:
        model = User
        fields = ('accountname', 'username', 'email', 'address', 'number', 'password1', 'password2')


class LoginForm(forms.Form):
    username = forms.CharField(
        label = "帳號",
        widget = forms.TextInput(attrs={'class': 'form-control'})
    )

    password = forms.CharField(
        label = "密碼",
        widget = forms.PasswordInput(attrs={'class': 'form-control'})
    )

CoffeeShop/Shopping/views.py
from django.shortcuts import render
from .models import Member, Order
from django.views import generic
from django.shortcuts import redirect
from .forms import RegisterForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.http.response import HttpResponse
import json
from NeoCoffee.models import Category
from django.http import JsonResponse
from django.contrib.auth.models import User

# Create your views here.

# def index(request):
#     num_coffee = coffee.objects.all().count()

#     context = {
#         'num_coffee' : num_coffee,
#     }

#     return render(request, 'home/index.html', context=context)


def sign_up(request):
    form = RegisterForm()

    if request.method == "POST":
        form = RegisterForm(request.POST)
        member_name = request.POST['username']
        member_email = request.POST['email']
        member_address = request.POST['address']
        member_number = request.POST['number']

        if form.is_valid():
            _member = Member(member_name=member_name, 
                             member_email=member_email,
                             member_address=member_address,
                             member_number=member_number,)
            _member.save()
            form.save()
            return redirect('/Shopping/login')
        
    context = {
        'form' : form
    }

    return render(request, 'accounts/register.html', context)

def sign_in(request):
    form = LoginForm()
    error_message = None

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')  #重新導向到首頁
        else:
            error_message = "帳號不存在或密碼錯誤"

    context = {
        'form' : form,
        'error_message': error_message
    }

    return render(request, 'accounts/login.html', context)


def log_out(request):
    logout(request)

    return render(request, 'accounts/logout.html')


def place_order(request):
    data = json.loads(request.body)
    category_id = data.get('category_id')

    # Fetch the corresponding member and category name.
    try:
        member_obj = Member.objects.get(member_name=request.user.username)
        category_name = Category.objects.get(id=category_id).name

        # Create a new order.
        Order.objects.create(member=member_obj, coffee_name=category_name)

        return JsonResponse({'success': True})

    except Member.DoesNotExist:
        return JsonResponse({'success': False, 'error': 'Member not found'})
    except Category.DoesNotExist:
        return JsonResponse({'success': False, 'error': 'Category not found'})
    
def order_list(request):
    orders = Order.objects.all()
    return render(request, 'orders/order_list.html', {'orders': orders})

CoffeeShop/Shopping/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>Coffee Shop</h1>
    <h3>登入</h3>

    {% if error_message %}
        <div class="alert alert-danger">
            {{ error_message }}
        </div>
    {% endif %}

    <form action="" method="POST" class="mt-3">
        {% csrf_token %}
        <div class="form-group">
            {{ form.username.label_tag }} {{ form.username }}
        </div>
        <div class="form-group">
            {{ form.password.label_tag }} {{ form.password }}
        </div>
        
        <button type="submit" class="btn btn-primary">登入</button>
    </form>
    <p class="mt-3">還沒有帳號嗎? <a href="{% url 'Shopping:Register' %}">註冊</a></p>
</div>
{% endblock  %}

CoffeeShop/Shopping/templates/accounts/logout.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="jumbotron">
        <h1 class="display-4">Coffee Shop HomePage</h1>
        <p class="lead">Log out.</p>
        <hr class="my-4">
        <a class="btn btn-primary btn-lg" href="{% url 'Shopping:Login' %}" role="button">登入</a>
    </div>
</div>
{% endblock  %}

CoffeeShop/Shopping/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>萬有咖啡館</h1>
    <h3>註冊</h3>

    <form action="" method="POST" class="mt-3">
        {% csrf_token %}
        <div class="form-group">
            {{ form.accountname.label_tag }} {{ form.accountname }}
        </div>
        <div class="form-group">
            {{ form.username.label_tag }} {{ form.username }}
        </div>
        <div class="form-group">
            {{ form.email.label_tag }} {{ form.email }}
        </div>
        <div class="form-group">
            {{ form.address.label_tag }} {{ form.address }}
        </div>
        <div class="form-group">
            {{ form.number.label_tag }} {{ form.number }}
        </div>
        <div class="form-group">
            {{ form.password1.label_tag }} {{ form.password1 }}
        </div>
        <div class="form-group">
            {{ form.password2.label_tag }} {{ form.password2 }}
        </div>
        <button type="submit" class="btn btn-success">註冊</button>
    </form>
</div>
{% endblock  %}